require("dotenv").config()
const mongoose = require("mongoose")
const stripe = require("stripe")(process.env.STRIPE_SECRET_KEY)
const Payment = require("../models/payment")
const { reconcile } = require("../services/payments")
;(async () => {
  const [paymentId, intentId] = process.argv.slice(2)
  if (!paymentId || !intentId) throw new Error("Usage: node scripts/reconcile.js <paymentId> <stripeIntentId>")
  await mongoose.connect(process.env.MONGO_URI)
  const payment = await Payment.findById(paymentId)
  if (!payment) throw new Error("Payment not found")
  await reconcile(payment, await stripe.paymentIntents.retrieve(intentId))
  console.log("Provider payment reconciled")
})().catch((err) => { console.error(err.message); process.exitCode = 1 }).finally(() => mongoose.disconnect())
