jest.mock("../models/user", () => ({ findOne: jest.fn() }))
jest.mock("argon2", () => ({ verify: jest.fn() }))
jest.mock("jsonwebtoken", () => ({ sign: jest.fn(() => "token") }))
const User = require("../models/user")
const argon2 = require("argon2")
const jwt = require("jsonwebtoken")
const router = require("../routes/user")
const invoke = require("../../tests/route-helper")
beforeEach(() => jest.clearAllMocks())
test("unknown user returns once without password verification", async () => {
  User.findOne.mockResolvedValue(null)
  const res = await invoke(router, "post", "/login", { body: { email: "missing@example.com", password: "password" } })
  expect(res.statusCode).toBe(400)
  expect(res.json).toHaveBeenCalledTimes(1)
  expect(argon2.verify).not.toHaveBeenCalled()
})
test("valid credentials return token", async () => {
  User.findOne.mockResolvedValue({ _id: "user", password: "hash" })
  argon2.verify.mockResolvedValue(true)
  const res = await invoke(router, "post", "/login", { body: { email: "user@example.com", password: "password" } })
  expect(res.body).toEqual({ token: "token" })
  expect(jwt.sign).toHaveBeenCalled()
})
test("malformed login does not query DB", async () => {
  const res = await invoke(router, "post", "/login", { body: { email: { $ne: null }, password: "password" } })
  expect(res.statusCode).toBe(400)
  expect(User.findOne).not.toHaveBeenCalled()
})
